# Use root/example as user/password credentials
version: '3.1'

services:
  neo4j:
    working_dir: /root
    image: neo4j:4.0.1  
    restart: always
    environment:
      NEO4J_AUTH: none
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      # - $PWD/data:/data
      # - $PWD/import:/var/lib/neo4j/import
      - $PWD:/root
